/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Queries */
        get: operations["list_queries_api_projects__project_id__queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/queries/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Import Queries */
        post: operations["bulk_import_queries_api_projects__project_id__queries_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/queries/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Query */
        delete: operations["delete_query_api_projects__project_id__queries__query_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_channels__channel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel_id}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channel Videos */
        get: operations["list_channel_videos_api_channels__channel_id__videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_api_videos__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel_id}/thumbnails/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Channel Thumbnails
         * @description Queue a ``thumbnail_download`` job for the channel's not-yet-stored thumbnails.
         *     Repeating the call while that job is active returns the same job (``created=false``).
         */
        post: operations["download_channel_thumbnails_api_channels__channel_id__thumbnails_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_images__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a queued/retrying job; a running one is asked to abort. Finished jobs => 409.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChannelDetail */
        ChannelDetail: {
            /** Id */
            id: number;
            /** Youtube Channel Id */
            youtube_channel_id: string;
            /** Url */
            url: string;
            /** Handle */
            handle: string | null;
            /** Title */
            title: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Country */
            country: string | null;
            /** Default Language */
            default_language: string | null;
            /** Subscriber Count */
            subscriber_count: number | null;
            /** Subscribers Hidden */
            subscribers_hidden: boolean;
            /** View Count */
            view_count: number | null;
            /** Video Count */
            video_count: number | null;
            /** Published At */
            published_at: string | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Is Demo */
            is_demo: boolean;
            /** Description */
            description: string;
            /** Custom Url */
            custom_url: string | null;
            /** Keywords */
            keywords: string[];
            /** Topic Categories */
            topic_categories: string[];
            /** Projects */
            projects: components["schemas"]["ProjectRef"][];
            /** Videos Stored */
            videos_stored: number;
        };
        /** ChannelOut */
        ChannelOut: {
            /** Id */
            id: number;
            /** Youtube Channel Id */
            youtube_channel_id: string;
            /** Url */
            url: string;
            /** Handle */
            handle: string | null;
            /** Title */
            title: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Country */
            country: string | null;
            /** Default Language */
            default_language: string | null;
            /** Subscriber Count */
            subscriber_count: number | null;
            /** Subscribers Hidden */
            subscribers_hidden: boolean;
            /** View Count */
            view_count: number | null;
            /** Video Count */
            video_count: number | null;
            /** Published At */
            published_at: string | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Is Demo */
            is_demo: boolean;
        };
        /**
         * ChannelSort
         * @enum {string}
         */
        ChannelSort: "subscribers" | "views" | "videos" | "title" | "published" | "discovered";
        /** EnqueueResult */
        EnqueueResult: {
            job: components["schemas"]["JobRunOut"] | null;
            /** Created */
            created: boolean;
            /** Items */
            items: number;
        };
        /**
         * FetchStatus
         * @enum {string}
         */
        FetchStatus: "pending" | "ok" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunDetail */
        JobRunDetail: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            status: components["schemas"]["JobStatus"];
            /** Queue */
            queue: string;
            /** Priority */
            priority: number;
            /** Progress Total */
            progress_total: number;
            /** Progress Done */
            progress_done: number;
            /** Attempts */
            attempts: number;
            /** Budget Usd */
            budget_usd: string | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /** Actual Cost Usd */
            actual_cost_usd: string;
            /** Parent Id */
            parent_id: number | null;
            /** Created By */
            created_by: number | null;
            /** Error Code */
            error_code: string | null;
            /** Error Human */
            error_human: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            status: components["schemas"]["JobStatus"];
            /** Queue */
            queue: string;
            /** Priority */
            priority: number;
            /** Progress Total */
            progress_total: number;
            /** Progress Done */
            progress_done: number;
            /** Attempts */
            attempts: number;
            /** Budget Usd */
            budget_usd: string | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /** Actual Cost Usd */
            actual_cost_usd: string;
            /** Parent Id */
            parent_id: number | null;
            /** Created By */
            created_by: number | null;
            /** Error Code */
            error_code: string | null;
            /** Error Human */
            error_human: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed" | "retrying" | "cancelled";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserOut"];
            workspace: components["schemas"]["WorkspaceOut"];
            role: components["schemas"]["WorkspaceRole"];
        };
        /** Page[ChannelOut] */
        Page_ChannelOut_: {
            /** Items */
            items: components["schemas"]["ChannelOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[JobRunOut] */
        Page_JobRunOut_: {
            /** Items */
            items: components["schemas"]["JobRunOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ProjectOut] */
        Page_ProjectOut_: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[QueryOut] */
        Page_QueryOut_: {
            /** Items */
            items: components["schemas"]["QueryOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[VideoOut] */
        Page_VideoOut_: {
            /** Items */
            items: components["schemas"]["VideoOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Description */
            description?: string | null;
            /** Language */
            language?: string | null;
            /** Region Code */
            region_code?: string | null;
            /** Results Per Query */
            results_per_query?: number | null;
            /** Search Depth */
            search_depth?: number | null;
            /** Published After */
            published_after?: string | null;
            /** Videos To Analyze */
            videos_to_analyze?: number | null;
            /** Filter Settings */
            filter_settings?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Language */
            language: string | null;
            /** Region Code */
            region_code: string | null;
            /** Results Per Query */
            results_per_query: number;
            /** Search Depth */
            search_depth: number;
            /** Published After */
            published_after: string | null;
            /** Videos To Analyze */
            videos_to_analyze: number;
            /** Filter Settings */
            filter_settings: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ProjectStatus"];
            /** Is Demo */
            is_demo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Queries Count
             * @default 0
             */
            queries_count: number;
            /**
             * Channels Count
             * @default 0
             */
            channels_count: number;
        };
        /** ProjectRef */
        ProjectRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Description */
            description?: string | null;
            /** Language */
            language?: string | null;
            /** Region Code */
            region_code?: string | null;
            /** Results Per Query */
            results_per_query?: number | null;
            /** Search Depth */
            search_depth?: number | null;
            /** Published After */
            published_after?: string | null;
            /** Videos To Analyze */
            videos_to_analyze?: number | null;
            /** Filter Settings */
            filter_settings?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /**
         * QueryBulkImport
         * @description Either ``queries`` (list) or ``text`` (one query per line, e.g. pasted from a spreadsheet).
         */
        QueryBulkImport: {
            /** Queries */
            queries?: string[] | null;
            /** Text */
            text?: string | null;
        };
        /** QueryBulkResult */
        QueryBulkResult: {
            /** Created */
            created: number;
            /** Duplicates */
            duplicates: number;
            /** Rejected */
            rejected: components["schemas"]["RejectedLine"][];
            /** Items */
            items: components["schemas"]["QueryOut"][];
        };
        /** QueryOut */
        QueryOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            status: components["schemas"]["QueryStatus"];
            /** Taxonomy Node Id */
            taxonomy_node_id: number | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Results Count */
            results_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * QueryStatus
         * @enum {string}
         */
        QueryStatus: "pending" | "running" | "done" | "failed";
        /** RejectedLine */
        RejectedLine: {
            /** Line */
            line: number;
            /** Value */
            value: string;
            /** Reason */
            reason: string;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** ThumbnailOut */
        ThumbnailOut: {
            fetch_status: components["schemas"]["FetchStatus"];
            /** Original Url */
            original_url: string;
            /** Image Asset Id */
            image_asset_id: number | null;
            /** Image Url */
            image_url: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoDetail */
        VideoDetail: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Youtube Video Id */
            youtube_video_id: string;
            /** Title */
            title: string;
            /** Published At */
            published_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Is Short */
            is_short: boolean | null;
            /** View Count */
            view_count: number | null;
            /** Like Count */
            like_count: number | null;
            /** Comment Count */
            comment_count: number | null;
            thumbnail?: components["schemas"]["ThumbnailOut"] | null;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Category Id */
            category_id: string | null;
        };
        /** VideoOut */
        VideoOut: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Youtube Video Id */
            youtube_video_id: string;
            /** Title */
            title: string;
            /** Published At */
            published_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Is Short */
            is_short: boolean | null;
            /** View Count */
            view_count: number | null;
            /** Like Count */
            like_count: number | null;
            /** Comment Count */
            comment_count: number | null;
            thumbnail?: components["schemas"]["ThumbnailOut"] | null;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * WorkspaceRole
         * @enum {string}
         */
        WorkspaceRole: "owner" | "admin" | "operator" | "viewer";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProjectStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_queries_api_projects__project_id__queries_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["QueryStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_QueryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_import_queries_api_projects__project_id__queries_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryBulkImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryBulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_query_api_projects__project_id__queries__query_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_channels_get: {
        parameters: {
            query?: {
                project_id?: number | null;
                q?: string | null;
                min_subscribers?: number | null;
                max_subscribers?: number | null;
                country?: string | null;
                sort?: components["schemas"]["ChannelSort"];
                order?: components["schemas"]["SortOrder"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ChannelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_api_channels__channel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channel_videos_api_channels__channel_id__videos_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VideoOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_channel_thumbnails_api_channels__channel_id__thumbnails_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_images__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/*": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
