"""phase3 ingestion metrics ai budgets

Revision ID: 4c8e1a7d2f90
Revises: 3b7f0e9c41d2
Create Date: 2026-10-01 20:54:01.841498+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '4c8e1a7d2f90'
down_revision: str | None = '3b7f0e9c41d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('api_model_id', sa.String(length=120), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('price_input_per_1m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_output_per_1m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_per_image', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('pricing_verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models')),
    sa.UniqueConstraint('key', name=op.f('uq_ai_models_key'))
    )
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_prompt_templates_name_version'))
    )
    op.create_table('budgets',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Enum('global', 'project', 'task', name='budget_scope'), nullable=False),
    sa.Column('scope_ref', sa.String(length=100), nullable=True),
    sa.Column('period', sa.Enum('day', 'month', 'total', name='budget_period'), nullable=False),
    sa.Column('limit_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_ai_operations', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'global') = (scope_ref IS NULL)", name=op.f('ck_budgets_scope_ref_matches')),
    sa.CheckConstraint('limit_usd IS NOT NULL OR max_ai_operations IS NOT NULL', name=op.f('ck_budgets_has_limit')),
    sa.CheckConstraint('limit_usd IS NULL OR limit_usd >= 0', name=op.f('ck_budgets_limit_nonneg')),
    sa.CheckConstraint('max_ai_operations IS NULL OR max_ai_operations >= 0', name=op.f('ck_budgets_ops_nonneg')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_budgets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('workspace_id', 'scope', 'scope_ref', 'period', name=op.f('uq_budgets_workspace_id_scope_scope_ref_period'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_budgets_workspace_id'), 'budgets', ['workspace_id'], unique=False)
    op.create_table('image_metrics',
    sa.Column('image_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('algo_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('work_width', sa.Integer(), nullable=False),
    sa.Column('work_height', sa.Integer(), nullable=False),
    sa.Column('letterbox_cropped', sa.Boolean(), nullable=False),
    sa.Column('luminance_mean', sa.Float(), nullable=False),
    sa.Column('contrast_rms', sa.Float(), nullable=False),
    sa.Column('colorfulness', sa.Float(), nullable=False),
    sa.Column('sharpness_laplacian', sa.Float(), nullable=False),
    sa.Column('edge_density', sa.Float(), nullable=False),
    sa.Column('saliency_center_ratio', sa.Float(), nullable=True),
    sa.Column('dominant_colors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.CheckConstraint('edge_density BETWEEN 0 AND 1', name=op.f('ck_image_metrics_edge_density_range')),
    sa.CheckConstraint('luminance_mean BETWEEN 0 AND 1', name=op.f('ck_image_metrics_luminance_range')),
    sa.CheckConstraint('saliency_center_ratio IS NULL OR saliency_center_ratio BETWEEN 0 AND 1', name=op.f('ck_image_metrics_saliency_range')),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], name=op.f('fk_image_metrics_image_asset_id_image_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_asset_id', name=op.f('pk_image_metrics'))
    )
    op.create_index(op.f('ix_image_metrics_colorfulness'), 'image_metrics', ['colorfulness'], unique=False)
    op.create_index(op.f('ix_image_metrics_contrast_rms'), 'image_metrics', ['contrast_rms'], unique=False)
    op.create_index(op.f('ix_image_metrics_luminance_mean'), 'image_metrics', ['luminance_mean'], unique=False)
    op.create_table('ai_calls',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('job_run_id', sa.BigInteger(), nullable=True),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_key', sa.String(length=60), nullable=False),
    sa.Column('api_model_id', sa.String(length=120), nullable=False),
    sa.Column('prompt_template_id', sa.BigInteger(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ok', 'repaired', 'invalid_output', 'refused', 'error', name='ai_call_status'), server_default='pending', nullable=False),
    sa.Column('input_ref', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('image_inputs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('image_outputs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('actual_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 1', name=op.f('ck_ai_calls_attempt_positive')),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], name=op.f('fk_ai_calls_job_run_id_job_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['search_projects.id'], name=op.f('fk_ai_calls_project_id_search_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], name=op.f('fk_ai_calls_prompt_template_id_prompt_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ai_calls_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_calls'))
    )
    op.create_index(op.f('ix_ai_calls_job_run_id'), 'ai_calls', ['job_run_id'], unique=False)
    op.create_index('ix_ai_calls_task_created', 'ai_calls', ['task', 'created_at'], unique=False)
    op.create_index('ix_ai_calls_workspace_created', 'ai_calls', ['workspace_id', 'created_at'], unique=False)
    op.alter_column('job_runs', 'budget_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=14, scale=6),
               existing_nullable=True)
    op.alter_column('job_runs', 'estimated_cost_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=14, scale=6),
               existing_nullable=True)
    op.alter_column('job_runs', 'actual_cost_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=14, scale=6),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.add_column('search_projects', sa.Column('prefilter_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_projects', 'prefilter_settings')
    op.alter_column('job_runs', 'actual_cost_usd',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('job_runs', 'estimated_cost_usd',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('job_runs', 'budget_usd',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.drop_index('ix_ai_calls_workspace_created', table_name='ai_calls')
    op.drop_index('ix_ai_calls_task_created', table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_job_run_id'), table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_index(op.f('ix_image_metrics_luminance_mean'), table_name='image_metrics')
    op.drop_index(op.f('ix_image_metrics_contrast_rms'), table_name='image_metrics')
    op.drop_index(op.f('ix_image_metrics_colorfulness'), table_name='image_metrics')
    op.drop_table('image_metrics')
    op.drop_index(op.f('ix_budgets_workspace_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('prompt_templates')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
    # create_table created these enum types implicitly; drop_table does not remove them
    for name in ('ai_call_status', 'budget_period', 'budget_scope'):
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)
