"""ai model prices 6 decimals

Revision ID: 0d773a65d5b6
Revises: 4c8e1a7d2f90
Create Date: 2026-10-01 23:48:18.832258+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0d773a65d5b6'
down_revision: str | None = '4c8e1a7d2f90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_models', 'price_input_per_1m',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('ai_models', 'price_output_per_1m',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_models', 'price_output_per_1m',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('ai_models', 'price_input_per_1m',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
