"""baseline phase1

Revision ID: 7d1e52c3ac29
Revises: 
Create Date: 2026-09-24 01:42:51.139394+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '7d1e52c3ac29'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_TYPES = (
    "image_source", "taxonomy_level", "job_status", "project_status", "workspace_role",
    "query_status", "fetch_status", "discovery_method",
)


def upgrade() -> None:
    # Trusted extensions: can be created by the database owner (no superuser needed).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('handle', postgresql.CITEXT(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('custom_url', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('default_language', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('uploads_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('subscribers_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('topic_categories', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('last_fetched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('youtube_channel_id', name=op.f('uq_channels_youtube_channel_id'))
    )
    op.create_index(op.f('ix_channels_handle'), 'channels', ['handle'], unique=False)
    op.create_index(op.f('ix_channels_subscriber_count'), 'channels', ['subscriber_count'], unique=False)
    op.create_index('ix_channels_title_trgm', 'channels', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_channels_video_count'), 'channels', ['video_count'], unique=False)
    op.create_index(op.f('ix_channels_view_count'), 'channels', ['view_count'], unique=False)
    op.create_table('image_assets',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.BigInteger(), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('youtube_thumbnail', 'generated', 'reference', 'upload', 'demo', name='image_source'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_assets')),
    sa.UniqueConstraint('sha256', name=op.f('uq_image_assets_sha256'))
    )
    op.create_index(op.f('ix_image_assets_phash'), 'image_assets', ['phash'], unique=False)
    op.create_table('taxonomy_nodes',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.Enum('niche', 'topic', 'subtopic', name='taxonomy_level'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_nodes.id'], name=op.f('fk_taxonomy_nodes_parent_id_taxonomy_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxonomy_nodes')),
    sa.UniqueConstraint('parent_id', 'slug', name=op.f('uq_taxonomy_nodes_parent_id_slug'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_logs_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('channel_stats_snapshots',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_stats_snapshots_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_stats_snapshots')),
    sa.UniqueConstraint('channel_id', 'captured_on', name=op.f('uq_channel_stats_snapshots_channel_id_captured_on'))
    )
    op.create_table('job_runs',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'retrying', 'cancelled', name='job_status'), server_default='queued', nullable=False),
    sa.Column('queue', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('progress_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_cost_usd', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('procrastinate_job_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_human', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_job_runs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['job_runs.id'], name=op.f('fk_job_runs_parent_id_job_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_job_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_undispatched', 'job_runs', ['id'], unique=False, postgresql_where=sa.text("status = 'queued' AND procrastinate_job_id IS NULL"))
    op.create_index('ix_job_runs_workspace_created', 'job_runs', ['workspace_id', 'created_at'], unique=False)
    op.create_index('uq_job_runs_active_fingerprint', 'job_runs', ['fingerprint'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running', 'retrying')"))
    op.create_table('search_projects',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region_code', sa.String(length=2), nullable=True),
    sa.Column('results_per_query', sa.Integer(), server_default='50', nullable=False),
    sa.Column('search_depth', sa.Integer(), server_default='1', nullable=False),
    sa.Column('published_after', sa.Date(), nullable=True),
    sa.Column('videos_to_analyze', sa.Integer(), server_default='12', nullable=False),
    sa.Column('filter_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status'), server_default='active', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('results_per_query BETWEEN 1 AND 500', name=op.f('ck_search_projects_results_per_query_range')),
    sa.CheckConstraint('search_depth BETWEEN 1 AND 10', name=op.f('ck_search_projects_search_depth_range')),
    sa.CheckConstraint('videos_to_analyze BETWEEN 1 AND 50', name=op.f('ck_search_projects_videos_to_analyze_range')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_search_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_projects')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_search_projects_workspace_id_name'))
    )
    op.create_table('secrets',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_secrets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets'))
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('videos',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.String(length=10), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('last_fetched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_videos_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos')),
    sa.UniqueConstraint('youtube_video_id', name=op.f('uq_videos_youtube_video_id'))
    )
    op.create_index('ix_videos_channel_published', 'videos', ['channel_id', 'published_at'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'operator', 'viewer', name='workspace_role'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_members_workspace_id_user_id'))
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_table('project_channels',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('first_discovered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_discovered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('discovery_count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_project_channels_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['search_projects.id'], name=op.f('fk_project_channels_project_id_search_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'channel_id', name=op.f('pk_project_channels'))
    )
    op.create_index(op.f('ix_project_channels_channel_id'), 'project_channels', ['channel_id'], unique=False)
    op.create_table('project_niches',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('taxonomy_node_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['search_projects.id'], name=op.f('fk_project_niches_project_id_search_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_nodes.id'], name=op.f('fk_project_niches_taxonomy_node_id_taxonomy_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'taxonomy_node_id', name=op.f('pk_project_niches'))
    )
    op.create_table('search_queries',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('text_normalized', sa.String(length=300), nullable=False),
    sa.Column('taxonomy_node_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='query_status'), server_default='pending', nullable=False),
    sa.Column('last_run_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('results_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['search_projects.id'], name=op.f('fk_search_queries_project_id_search_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_nodes.id'], name=op.f('fk_search_queries_taxonomy_node_id_taxonomy_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries')),
    sa.UniqueConstraint('project_id', 'text_normalized', name=op.f('uq_search_queries_project_id_text_normalized'))
    )
    op.create_index(op.f('ix_search_queries_project_id'), 'search_queries', ['project_id'], unique=False)
    op.create_table('thumbnails',
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('image_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('fetch_status', sa.Enum('pending', 'ok', 'failed', name='fetch_status'), server_default='pending', nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], name=op.f('fk_thumbnails_image_asset_id_image_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_thumbnails_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thumbnails')),
    sa.UniqueConstraint('video_id', name=op.f('uq_thumbnails_video_id'))
    )
    op.create_index(op.f('ix_thumbnails_image_asset_id'), 'thumbnails', ['image_asset_id'], unique=False)
    op.create_table('video_stats_snapshots',
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_stats_snapshots_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_stats_snapshots')),
    sa.UniqueConstraint('video_id', 'captured_on', name=op.f('uq_video_stats_snapshots_video_id_captured_on'))
    )
    op.create_table('channel_discoveries',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('search_query_id', sa.BigInteger(), nullable=True),
    sa.Column('source_video_id', sa.BigInteger(), nullable=True),
    sa.Column('method', sa.Enum('keyword_search', 'channel_search', 'related_video', 'manual_import', 'monitoring', 'demo', name='discovery_method'), nullable=False),
    sa.Column('discovered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_discoveries_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['search_projects.id'], name=op.f('fk_channel_discoveries_project_id_search_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], name=op.f('fk_channel_discoveries_search_query_id_search_queries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], name=op.f('fk_channel_discoveries_source_video_id_videos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_discoveries'))
    )
    op.create_index(op.f('ix_channel_discoveries_channel_id'), 'channel_discoveries', ['channel_id'], unique=False)
    op.create_index('uq_channel_discoveries_source', 'channel_discoveries', ['project_id', 'channel_id', 'search_query_id', 'source_video_id', 'method'], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_channel_discoveries_source', table_name='channel_discoveries', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_channel_discoveries_channel_id'), table_name='channel_discoveries')
    op.drop_table('channel_discoveries')
    op.drop_table('video_stats_snapshots')
    op.drop_index(op.f('ix_thumbnails_image_asset_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    op.drop_index(op.f('ix_search_queries_project_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_table('project_niches')
    op.drop_index(op.f('ix_project_channels_channel_id'), table_name='project_channels')
    op.drop_table('project_channels')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_videos_channel_published', table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('secrets')
    op.drop_table('search_projects')
    op.drop_index('uq_job_runs_active_fingerprint', table_name='job_runs', postgresql_where=sa.text("status IN ('queued', 'running', 'retrying')"))
    op.drop_index('ix_job_runs_workspace_created', table_name='job_runs')
    op.drop_index('ix_job_runs_undispatched', table_name='job_runs', postgresql_where=sa.text("status = 'queued' AND procrastinate_job_id IS NULL"))
    op.drop_table('job_runs')
    op.drop_table('channel_stats_snapshots')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('taxonomy_nodes')
    op.drop_index(op.f('ix_image_assets_phash'), table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_index(op.f('ix_channels_view_count'), table_name='channels')
    op.drop_index(op.f('ix_channels_video_count'), table_name='channels')
    op.drop_index('ix_channels_title_trgm', table_name='channels', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_channels_subscriber_count'), table_name='channels')
    op.drop_index(op.f('ix_channels_handle'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
    # Alembic autogenerate does not drop native enum types on downgrade.
    for name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {name}")
