"""phase2 discovery

Revision ID: 3b7f0e9c41d2
Revises: 2a59c3efc6c0
Create Date: 2026-10-01 15:33:43.790576+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# add_column does not create a native enum type by itself (create_table does).
search_type = postgresql.ENUM("video", "channel", name="search_type", create_type=False)

revision: str = '3b7f0e9c41d2'
down_revision: str | None = '2a59c3efc6c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_quota_ledger',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('quota_day', sa.Date(), nullable=False),
    sa.Column('units_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('units_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'quota_day', name=op.f('pk_youtube_quota_ledger'))
    )
    op.create_table('channel_metrics',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_videos', sa.Integer(), nullable=False),
    sa.Column('avg_views', sa.BigInteger(), nullable=True),
    sa.Column('median_views', sa.BigInteger(), nullable=True),
    sa.Column('last_video_views', sa.BigInteger(), nullable=True),
    sa.Column('avg_views_recent', sa.BigInteger(), nullable=True),
    sa.Column('views_to_subs_ratio', sa.Float(), nullable=True),
    sa.Column('median_views_to_subs_ratio', sa.Float(), nullable=True),
    sa.Column('videos_7d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('videos_30d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('videos_90d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_days_between_uploads', sa.Float(), nullable=True),
    sa.Column('last_video_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('oldest_window_video_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('upload_consistency', sa.Float(), nullable=True),
    sa.Column('views_trend', sa.Float(), nullable=True),
    sa.Column('recent_views_velocity', sa.Float(), nullable=True),
    sa.CheckConstraint('upload_consistency BETWEEN 0 AND 1', name=op.f('ck_channel_metrics_upload_consistency_range')),
    sa.CheckConstraint('window_videos >= 0', name=op.f('ck_channel_metrics_window_videos_nonneg')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_metrics_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_channel_metrics'))
    )
    op.create_index(op.f('ix_channel_metrics_avg_views'), 'channel_metrics', ['avg_views'], unique=False)
    op.create_index(op.f('ix_channel_metrics_last_video_at'), 'channel_metrics', ['last_video_at'], unique=False)
    op.create_index(op.f('ix_channel_metrics_median_views'), 'channel_metrics', ['median_views'], unique=False)
    op.create_index(op.f('ix_channel_metrics_videos_30d'), 'channel_metrics', ['videos_30d'], unique=False)
    op.create_index(op.f('ix_channel_metrics_views_to_subs_ratio'), 'channel_metrics', ['views_to_subs_ratio'], unique=False)
    search_type.create(op.get_bind(), checkfirst=True)
    op.add_column('search_queries', sa.Column('search_type', search_type, server_default='video', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'search_type')
    op.drop_index(op.f('ix_channel_metrics_views_to_subs_ratio'), table_name='channel_metrics')
    op.drop_index(op.f('ix_channel_metrics_videos_30d'), table_name='channel_metrics')
    op.drop_index(op.f('ix_channel_metrics_median_views'), table_name='channel_metrics')
    op.drop_index(op.f('ix_channel_metrics_last_video_at'), table_name='channel_metrics')
    op.drop_index(op.f('ix_channel_metrics_avg_views'), table_name='channel_metrics')
    op.drop_table('channel_metrics')
    op.drop_table('youtube_quota_ledger')
    # ### end Alembic commands ###
    search_type.drop(op.get_bind(), checkfirst=True)
